---
vswitch:
  ips:
    - '192.168.100.1' # kube1
    - '192.168.100.2' # kube2
    - '192.168.100.3' # hyper1
    - '192.168.100.4' # hyper2
  protocols_and_ports:
    - proto: 'tcp'
      port: '2379'
    - proto: 'tcp'
      port: '443'
    - proto: 'tcp'
      port: '2380'
    - proto: 'tcp'
      port: '6443'
    - proto: 'udp'
      port: '8472'
    - proto: 'tcp'
      port: '9099'
    - proto: 'tcp'
      port: '10250'
    - proto: 'tcp'
      port: '10254'
  vlan_id: 4000
  vlan_broadcast: 192.168.100.255
