---
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [
    "curl",
    "vim",
    "git",
    "apt-transport-https",
    "ca-certificates",
    "software-properties-common",
    "python3-pip",
    "virtualenv",
    "python3-setuptools",
    "tmux",
    "mosh",
    "xclip",
    "zsh",
    # "hub", #It is probably better to use the snap for this in the future
    # "fd-find",
    "nginx",
    "python-certbot-nginx",
  ]

fnm_nodejs_versions:
  - "latest-v12.x"

fnm_npm_global_packages:
  - name: ganache-cli
  - name: truffle
  - name: "@graphprotocol/graph-cli"
  - name: "@openzeppelin/cli"
  - name: "diff-so-fancy"

ssh_key_filename: id_rsa

dotfiles_commit: 5203a96

classic_snaps: [hub, go]
